import Head from "next/head";
import { generateText } from "./api/huggingface";
import { useState, useEffect } from "react";

export default function Home() {
	const [answer, setAnswer] = useState("");
	const [country, setCountry] = useState("");
	const [isLoading, setIsLoading] = useState(false);
	const onChange = (event) => {
		setCountry(event.target.value);
		setAnswer("");
	};
	const [time, setTime] = useState(0);
	const [running, setRunning] = useState(false);

	// Stopwatch timer
	useEffect(() => {
		let interval;
		if (running) {
			interval = setInterval(() => {
				setTime((prevTime) => prevTime + 10);
			}, 10);
		} else if (!running) {
			clearInterval(interval);
		}
		return () => clearInterval(interval);
	}, [running]);

	const prompt = (
		<>
			Olet AI-avustaja, joka on todella hyvä maantiedossa. Käyttäjä nimeää maan
			ja kerrot sen olevan pääkaupunki.
			<p>
				<br></br>Käyttäjä: Norja
				<br></br>AI-avustaja: Oslo
			</p>
			<p>
				<br></br>Käyttäjä: Saksa
				<br></br>AI-avustaja: Berliini
			</p>
			<p>
				<br></br>Käyttäjä: Yhdysvallat
				<br></br>AI-avustaja: Washington, D.C.
			</p>
			<p>
				<br></br>Käyttäjä:{" "}
				{country && (
					<mark className="p-1 font-semibold text-white bg-purple-600 rounded dark:bg-purple-500">
						{country}
					</mark>
				)}
				<br></br>AI-avustaja:{" "}
				{answer && (
					<mark className="p-1 font-semibold text-white bg-red-600 rounded dark:bg-red-500">
						{answer.generated_text}
					</mark>
				)}
			</p>
		</>
	);

	const textGeneration = async () => {
		setIsLoading(true);

		const input = `Olet AI-avustaja, joka on todella hyvä maantiedossa. Käyttäjä nimeää maan
		 ja kerrot sen olevan pääkaupunki.
				
		 Käyttäjä: Norja 
		 AI-avustaja:Oslo 
		 
		 Käyttäjä: Saksa 
		 AI-avustaja: Berliini

		 Käyttäjä: Yhdysvallat
		 AI-avustaja: Washington, D.C.		
				
		 Käyttäjä: ${country}
		 AI-avustaja:`;

		const result = await generateText(input);
		setAnswer(result);
		setIsLoading(false);
		setRunning(false);
		setTime(0);
	};

	const githubLink = () => {
		window.open("https://github.com/niknorf/capital-gpt3-finnish-3B");
	};

	return (
		<>
			<Head>
				<title>gpt3-finnish-3B</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="container mx-auto px-4 max-w-3xl">
					<h1 className="flex mt-6 items-center text-5xl font-extrabold dark:text-white">
						Model
						<span className="bg-blue-100 text-blue-800 md:text-2xl text-xl font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ml-2">
							TurkuNLP/gpt3-finnish-3B
						</span>
					</h1>
					<p className="mb-7 mt-4 text-lg font-normal text-gray-500 lg:text-xl dark:text-gray-400">
						🤗 Hugging Face:{" "}
						<a
							href="https://huggingface.co/TurkuNLP/gpt3-finnish-3B"
							target="_blank"
							className="font-medium text-blue-600 dark:text-blue-500 hover:underline"
						>
							repo
						</a>
					</p>
					<h5 className="text-xl font-bold dark:text-white">Prompt:</h5>
					<div className="p-4 my-4 bg-slate-200 rounded-xl border-2 border-slate-400">
						<code>{prompt}</code>
					</div>
					<h5 className="text-xl mb-4 font-bold dark:text-whit">
						Valitse maa:
					</h5>
					<button
						onClick={() => {
							setCountry("Suomi");
							setAnswer("");
						}}
						className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800"
					>
						<span className="relative text-3xl px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
							🇫🇮
						</span>
					</button>
					<button
						onClick={() => {
							setCountry("Ruotsi");
							setAnswer("");
						}}
						className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-200 via-red-300 to-yellow-200 group-hover:from-red-200 group-hover:via-red-300 group-hover:to-yellow-200 dark:text-white dark:hover:text-gray-900 focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400"
					>
						<span className="relative text-3xl px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
							🇸🇪
						</span>
					</button>
					<button
						onClick={() => {
							setCountry("Tanska");
							setAnswer("");
						}}
						className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-pink-500 to-orange-400 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800"
					>
						<span className="relative text-3xl px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
							🇩🇰
						</span>
					</button>
					<h5 className="text-xl mt-2 mb-4 font-bold dark:text-whit">
						Tai kirjoita:
					</h5>
					<div className="lg:flex lg:flex-row lg:items-end">
						<div className="pb-1.5 mr-1">
							<input
								value={country}
								onChange={onChange}
								type="text"
								id="default-input"
								className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
							/>
						</div>
						<div>
							<button
								onClick={() => {
									setRunning(true);
									textGeneration();
								}}
								type="button"
								className="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2"
							>
								<span className="w-5 h-5 mr-2 -ml-1">🌍</span>
								Nimeä pääkaupunki
							</button>
						</div>
					</div>
					{isLoading && (
						<div>
							<div className="mt-3">
								<div
									className="flex p-4 mb-4 text-sm text-yellow-800 border border-yellow-300 rounded-lg bg-yellow-50 dark:bg-gray-800 dark:text-yellow-300 dark:border-yellow-800"
									role="alert"
								>
									<svg
										aria-hidden="true"
										className="flex-shrink-0 inline w-5 h-5 mr-3"
										fill="currentColor"
										viewBox="0 0 20 20"
										xmlns="http://www.w3.org/2000/svg"
									>
										<path
											fill-rule="evenodd"
											d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
											clip-rule="evenodd"
										></path>
									</svg>
									<span className="sr-only">Info</span>
									<div>
										The model is hosted on the free Hugging Face instance. The
										initial non-cached inference might take up to 1,5 minutes.
									</div>
								</div>
							</div>
							<div role="status" className="mt-3 flex items-center">
								<svg
									aria-hidden="true"
									className="inline w-10 h-10 mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600"
									viewBox="0 0 100 101"
									fill="none"
									xmlns="http://www.w3.org/2000/svg"
								>
									<path
										d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
										fill="currentColor"
									/>
									<path
										d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
										fill="currentFill"
									/>
								</svg>
								<div className="ml-2">
									<span>
										{("0" + Math.floor((time / 60000) % 60)).slice(-2)}:
									</span>
									<span>
										{("0" + Math.floor((time / 1000) % 60)).slice(-2)}:
									</span>
									<span>{("0" + ((time / 10) % 100)).slice(-2)}</span>
								</div>
								<span className="sr-only">Loading...</span>
							</div>
						</div>
					)}{" "}
					{answer && (
						<div className="flex mt-4 items-center">
							<h5 className="text-xl font-bold dark:text-white">
								Pääkaupunki:
							</h5>{" "}
							<span> 📍{answer.generated_text}</span>
						</div>
					)}
					<div className="fixed bottom-0 right-0 transform translate-x-2">
						<button
							type="button"
							onClick={githubLink}
							className="text-white mb-7 mr-9 bg-[#24292F] hover:bg-[#24292F]/90 focus:ring-4 focus:outline-none focus:ring-[#24292F]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-gray-500 dark:hover:bg-[#050708]/30"
						>
							<svg
								className="w-4 h-4 mr-2 -ml-1"
								aria-hidden="true"
								focusable="false"
								data-prefix="fab"
								data-icon="github"
								role="img"
								xmlns="http://www.w3.org/2000/svg"
								viewBox="0 0 496 512"
							>
								<path
									fill="currentColor"
									d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3 .3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5 .3-6.2 2.3zm44.2-1.7c-2.9 .7-4.9 2.6-4.6 4.9 .3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3 .7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3 .3 2.9 2.3 3.9 1.6 1 3.6 .7 4.3-.7 .7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3 .7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3 .7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"
								></path>
							</svg>
							Source code on GitHub
						</button>
					</div>
				</div>
			</main>
		</>
	);
}
